name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository 🎉
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup pnpm 📦
        uses: pnpm/action-setup@v6

      - name: Setup Node.js 🟢
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies 🚀
        run: pnpm install --frozen-lockfile

      - name: Run linter 👀
        run: pnpm run lint

      - name: Build the package 🎉
        run: pnpm run build
